# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install Nodejs
      uses: actions/setup-node@v2
      with:
         node-version: '14'
    - name: Install Selenium Side Runner
      run: |
        npm install -g selenium-side-runner
    - name: Install Chrome
      run: |
        apt install google-chrome-stable
    - name: Install seleniumbase
      run: pip install seleniumbase
    - name: Install chromedriver
      run: |
        seleniumbase install chromedriver
    - name: Run Tests
      run: |
        selenium-side-runner project.side
